# -*- coding: utf-8 -*-
from __future__ import annotations

import re
import zipfile
from pathlib import Path
import xml.etree.ElementTree as ET


TEMPLATE = Path(r"C:\Users\BarryZ\Downloads\位置服务与实践-课程汇报ppt.pptx")
OUTPUT = Path(r"C:\Users\BarryZ\Desktop\codextest\PDR程序讲解汇报_自动生成.pptx")

NS = {
    "a": "http://schemas.openxmlformats.org/drawingml/2006/main",
    "p": "http://schemas.openxmlformats.org/presentationml/2006/main",
    "r": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
}

for prefix, uri in NS.items():
    ET.register_namespace(prefix, uri)


SLIDE_TEXTS = {
    1: [
        "2026",
        "基于 Android 九轴 IMU 的实时",
        "PDR",
        "定位程序讲解",
        "开发过程、算法原理、实验设计与评价分析",
    ],
    2: [
        "项目摘要",
        "Android Studio 工程可运行",
        "实时 IMU 采集",
        "九轴 / 六轴姿态滤波",
        "脚步探测与步长估计",
        "中断检查与磁场修正",
        "位置递推与地图显示",
        "CSV 实时数据输出",
        "中文 UI 与可折叠面板",
        "实验页预留",
        "评价方法与局限分析",
    ],
    3: [
        "",
        "目   录",
        "项目概述与开发过程",
        "1",
        "实时 PDR 核心原理",
        "2",
        "",
        "工程实现与界面设计",
        "3",
        "实验设计、评价与局限",
        "4",
        "",
    ],
    4: [
        "1.",
        "项目概述：系统目标",
        "软件命名",
        "Android-PDR",
        "（手机端实时航迹推算演示程序）",
        "",
        "实现功能",
        "实现对手机加速度计、陀螺仪、磁力计等数据采集",
        "实现实时行人航迹推算",
        "实现位置结果、方向标志和地图显示",
        "实现实时日志输出与实验复盘",
        "实现方式一：手机采集 + 手机端实时解算",
        "实现方式二：GPS 辅助修正 + 本地 CSV 记录",
        "系统特性",
        "中文 UI、高清地图、可折叠工作区",
        "可选择六轴或九轴 AHRS 模式",
        "可选择是否显示系统计步器",
        "支持删除手机本地日志和地图缓存",
        "支持 Android Studio Preview",
        "支持 assembleDebug 构建验证",
        "",
    ],
    5: [
        "1.",
        "开发过程：系统架构",
        "系统架构：传感器层 → PDR 引擎层 → 地图与日志层",
    ],
    6: [
        "2.",
        "开发过程：关键迭代",
        "开发过程",
        "先依据课程 PPT 梳理完整链路",
        "再重写 NineAxisPdrEngine 统一算法入口",
        "随后重构 MainActivity 接入 GPS、地图与实时输出",
        "扩展 ImuCsvLogger 记录原始与衍生状态",
        "补足 Compose Preview 与权限检查",
        "最后完成 Android Studio 编译验证",
        "",
        "",
        "工程文件",
        "MainActivity.kt",
        "NineAxisPdrEngine.kt",
        "ImuCsvLogger.kt",
        "CoordinateTransformUtil.kt",
        "",
        "现阶段结果",
        "已可在手机端进行实时 PDR 显示",
        "已具备实验与汇报基础",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    7: [
        "2.",
        "传感器数据获取：手机端采集与实时输出",
        "数据采集",
        "利用手机传感器 API 接口获取数据",
        "",
        "实时输出",
        "接受实时数据并记录时间戳、姿态角、步频、步长、位置等中间量",
        "",
        "采集来源",
        "加速度计",
        "陀螺仪",
        "磁力计",
        "系统计步器",
        "GPS / 速度 / bearing",
        "",
        "程序实现",
        "SensorManager + FusedLocationProvider",
        "以加速度事件为主时间轴融合最近陀螺仪和磁力计",
        "CSV 日志同步写入原始数据与处理状态",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    8: [
        "2.",
        "实时行人航迹推算：数据预处理",
        "数据预处理",
        "",
        "课程方案建议",
        "线性插值统一时间",
        "",
        "当前实现",
        "三类传感器采样频率不稳定，当前版本采用加速度主时间轴同步",
        "并对加速度、陀螺仪、磁力数据做一阶平滑",
        "PDR",
        "算法要求传感器数据时间尽量同步",
        "",
        "优点",
        "实现简单，实时性强",
        "适合手机端在线运行",
        "",
        "局限",
        "还未做严格重采样与完整线性插值",
        "后续可继续增强时间对齐精度",
        "",
        "",
        "",
        "",
        "",
        "",
    ],
    9: [
        "3.",
        "实时行人航迹推算：航向与位置初始化",
        "初始化处理（航向初始化）",
        "设备静止时先等待 GPS 锁定起点",
        "",
        "根据位置 bearing 或初始姿态估计航向",
        "若设备无磁力计则自动切换为六轴模式",
        "根据水平姿态角计算磁力计的水平输出",
        "根据磁力计的水平输出计算磁北航向",
        "根据当地磁偏角 D 可继续做航向修正",
        "",
        "初始化结果",
        "建立起点、初始 heading 和局部平面坐标基准",
    ],
    10: [
        "3.",
        "实时行人航迹推算：实时数据输出与状态管理",
        "实时输出（状态面板）",
        "实时显示 roll / pitch / yaw / heading",
        "实时显示步数、步频、步长、步间隔",
        "实时显示 GPS 精度、速度和 IMU 采样率",
        "实时显示中断状态、修正来源、磁场模值",
        "",
        "日志输出",
        "CSV 记录 timestamp、ax~mz、ahrs_mode、heading_deg",
        "记录 total_steps、cadence_spm、step_frequency_hz",
        "记录 last_step_length_m、east_m、north_m、lat、lon",
        "",
        "界面意义",
        "便于调参、实验复盘和答辩展示",
        "",
    ],
    11: [
        "3.",
        "实时行人航迹推算：姿态滤波（",
        "AHRS",
        "六轴）",
        "姿态滤波（",
        "AHRS",
        "六轴）",
        "根据上一时刻的四元数信息求解",
        "地球重力场",
        "方向",
        "",
        "根据",
        "加速度观测与估计重力做误差反馈",
        "利用 PI 校正项补偿陀螺仪积分漂移",
        "姿态表示采用四元数，避免欧拉角万向锁",
        "",
        "程序实现",
        "updateSixAxis()",
        "gravityVector()",
        "roll / pitch / yaw 输出",
        "",
        "特点",
        "磁干扰环境下更稳健",
        "但长期运行偏航角可能漂移",
        "",
        "",
        "",
        "",
        "",
    ],
    12: [
        "3.",
        "实时行人航迹推算：姿态滤波（",
        "AHRS",
        "九轴）",
        "姿态滤波（",
        "AHRS",
        "九轴）",
        "根据上一时刻的四元数以及磁力信息求解",
        "地球重力场和磁场",
        "方向",
        "",
        "根据",
        "磁场观测补偿偏航角漂移",
        "将重力与磁场联合参与误差求解",
        "中断后若磁场可靠，可执行航向重对准",
        "",
        "程序实现",
        "updateNineAxis()",
        "realignHeadingFromMagnetic()",
        "GPS heading 辅助修正",
        "",
        "特点",
        "长路径和多转弯场景更有优势",
        "但受磁扰动影响，需要异常场景判断",
        "",
        "",
        "",
        "",
        "",
    ],
    13: [
        "3.",
        "实时行人航迹推算：脚步处理（步频探测）",
        "脚步处理（步频探测）",
        "根据姿态解算结果计算垂向加速度",
        "",
        "使用连续三个历元的垂向加速度探测脚步",
        "",
        "进行峰值探测",
        "当上一个历元的数据大于本历元和上上个历元的数据，并且大于一个",
        "可调节阈值",
        "时，认为这个历元可能出现了脚步",
        "",
        "程序还结合陀螺仪模值过滤弱运动伪峰",
        "阈值随信号幅值自适应更新",
        "并在合理区间内进行约束",
        "",
        "",
    ],
    14: [
        "3.",
        "实时行人航迹推算：脚步处理（步长估计）",
        "脚步处理（步长估计）",
        "计算步频",
        "为消弱脚步探测错误对步长的影响，将本次脚步时间",
        "间隔与上一次脚步时间间隔综合求算",
        "",
        "结合身高估计补偿",
        "程序中还融合波峰幅值项，并将步长限制在经验范围内",
    ],
    15: [
        "3.",
        "实时行人航迹推算：位置更新（坐标与递推）",
        "位置更新（坐标转换）",
        "大地坐标系转局部东-北平面坐标系",
        "为保证程序的兼容性和可扩展性，程序会在局部平面坐标系下更新位置",
        "",
        "位置更新（递推计算）",
        "将探测得到的脚步与此时刻的航向角对应",
        "根据方位角和步长以及上一时刻的位置递推计算下一时刻的位置",
        "GPS 精度较高时再进行轻量位置与航向辅助修正",
    ],
    16: [
        "3.",
        "实时行人航迹推算：中断检查与中断修正",
        "中断检查",
        "为保证步长估计更加稳健，需要设计脚步中断检查",
        "本次脚步和上次脚步之间的时间差大于 1.5 s 时认为发生中断",
        "若磁场可靠，则触发磁航向重对准并继续位置递推",
    ],
    17: [
        "3.",
        "工程实现：界面优化与 Android Studio 预览",
        "界面优化",
        "",
        "采用顶部状态条 + 中央地图 + 底部折叠工作区",
        "",
        "加入高清地图、方向标志、中文 UI、可选计步器",
        "加入删除手机存储日志与缓存的按钮",
        "加入航向标志、实时数据面板和修正来源显示",
        "避免信息堆叠，使界面不臃肿",
        "Android Studio 预览",
        "抽离 Preview 版本地图占位图",
        "可在不启动真机的情况下预览界面",
        "并支持 assembleDebug 构建",
        "",
        "程序文件",
        "MainActivity.kt / PdrDashboardPreview()",
        "",
        "",
        "",
        "",
    ],
    18: [
        "4.",
        "实验过程与结果（待补充）",
        "实验过程记录",
        "此页预留：设备型号、实验场景、路径示意、持机方式",
        "结果展示",
        "此页预留：轨迹图、误差表、对比图、结论",
    ],
    19: [
        "4.",
        "评价方法、优点与局限性",
        "评价指标：轨迹误差、终点误差、步数误差、航向偏差、实时性",
        "优点：低成本、纯手机端、实时输出完整、工程化程度较高",
        "局限：磁扰影响、参数经验性强、时间同步仍可继续优化",
        "后续：地图约束、零速更新、卡尔曼滤波、数据集对比",
        "年位置基础与服务课程设计",
    ],
    20: [
        "附录：后续改进方向",
        "实时",
        "PDR",
        "后续可提升点",
        "步长探测时阈值可继续自适应",
        "",
        "数据平滑方式可继续增强",
        "",
        "加入严格线性插值与统一采样频率",
        "加入地图匹配与更多先验约束",
        "加入离线回放与实验报告自动统计",
        "加入不同持机姿态识别与参数自适应",
        "",
        "谢谢观看",
    ],
}


def rewrite_slide_xml(data: bytes, texts: list[str]) -> bytes:
    root = ET.fromstring(data)
    nodes = root.findall(".//a:t", NS)
    for index, node in enumerate(nodes):
        node.text = texts[index] if index < len(texts) else ""
    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


def main() -> None:
    if not TEMPLATE.exists():
        raise FileNotFoundError(f"template not found: {TEMPLATE}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    if OUTPUT.exists():
        OUTPUT.unlink()

    slide_re = re.compile(r"ppt/slides/slide(\d+)\.xml$")
    with zipfile.ZipFile(TEMPLATE, "r") as zin, zipfile.ZipFile(
        OUTPUT, "w", compression=zipfile.ZIP_DEFLATED
    ) as zout:
        for info in zin.infolist():
            data = zin.read(info.filename)
            match = slide_re.match(info.filename)
            if match:
                slide_no = int(match.group(1))
                texts = SLIDE_TEXTS.get(slide_no)
                if texts is not None:
                    data = rewrite_slide_xml(data, texts)
            zout.writestr(info, data)

    print(f"PPT_CREATED: {OUTPUT}")


if __name__ == "__main__":
    main()
